/**
 * Recurring Bookings Service
 *
 * Handles recurring booking operations with Supabase backend.
 * Enables pattern-based recurring reservations with occurrence management.
 *
 * Features:
 * - Create recurring booking series
 * - Manage individual occurrences
 * - Confirm/skip occurrences
 * - Pause/cancel series
 * - Discount support
 */

import { supabase } from '@/lib/supabase';
import type { Database } from '@/types/database';
import { useQuery, useMutation, useQueryClient, type UseQueryResult, type UseMutationResult } from '@tanstack/react-query';

// Type aliases
type RecurringBooking = Database['public']['Tables']['recurring_bookings']['Row'];
type RecurringBookingInsert = Database['public']['Tables']['recurring_bookings']['Insert'];
type RecurringBookingUpdate = Database['public']['Tables']['recurring_bookings']['Update'];
type RecurringOccurrence = Database['public']['Tables']['recurring_booking_occurrences']['Row'];

/**
 * Recurring booking with occurrences
 */
export interface RecurringBookingWithOccurrences extends RecurringBooking {
  readonly occurrences: readonly RecurringOccurrence[];
}

/**
 * Query keys
 */
export const recurringKeys = {
  all: ['recurring'] as const,
  lists: () => [...recurringKeys.all, 'list'] as const,
  userRecurring: (userId: string) => [...recurringKeys.lists(), 'user', userId] as const,
  facilityRecurring: (facilityId: string) => [...recurringKeys.lists(), 'facility', facilityId] as const,
  details: () => [...recurringKeys.all, 'detail'] as const,
  detail: (id: string) => [...recurringKeys.details(), id] as const,
  withOccurrences: (id: string) => [...recurringKeys.detail(id), 'occurrences'] as const,
  occurrences: (id: string) => [...recurringKeys.detail(id), 'occurrences'] as const,
};

// ============================================================================
// Service Functions
// ============================================================================

export const recurringService = {
  /**
   * Fetch user's recurring bookings
   */
  async getUserRecurring(userId: string): Promise<RecurringBookingWithOccurrences[]> {
    const { data, error } = await supabase
      .from('recurring_bookings')
      .select(`
        *,
        occurrences:recurring_booking_occurrences (*)
      `)
      .eq('user_id', userId)
      .order('created_at', { ascending: false });

    if (error) throw error;
    return data as RecurringBookingWithOccurrences[];
  },

  /**
   * Fetch a single recurring booking with occurrences
   */
  async getById(id: string): Promise<RecurringBookingWithOccurrences> {
    const { data, error } = await supabase
      .from('recurring_bookings')
      .select(`
        *,
        occurrences:recurring_booking_occurrences (*)
      `)
      .eq('id', id)
      .single();

    if (error) throw error;
    return data as RecurringBookingWithOccurrences[];
  },

  /**
   * Create a recurring booking
   */
  async create(recurring: RecurringBookingInsert): Promise<RecurringBooking> {
    const { data, error } = await supabase
      .from('recurring_bookings')
      .insert(recurring)
      .select()
      .single();

    if (error) throw error;

    // Occurrences are auto-generated by trigger
    return data;
  },

  /**
   * Update a recurring booking
   */
  async update(id: string, updates: RecurringBookingUpdate): Promise<RecurringBooking> {
    const { data, error } = await supabase
      .from('recurring_bookings')
      .update(updates)
      .eq('id', id)
      .select()
      .single();

    if (error) throw error;
    return data;
  },

  /**
   * Pause a recurring booking series
   */
  async pause(id: string): Promise<RecurringBooking> {
    return this.update(id, { status: 'paused' });
  },

  /**
   * Resume a paused recurring booking
   */
  async resume(id: string): Promise<RecurringBooking> {
    return this.update(id, { status: 'active' });
  },

  /**
   * Cancel a recurring booking series
   */
  async cancel(id: string): Promise<RecurringBooking> {
    return this.update(id, { status: 'cancelled', end_date: new Date().toISOString() });
  },

  /**
   * Get occurrences for a recurring booking
   */
  async getOccurrences(recurringId: string): Promise<RecurringOccurrence[]> {
    const { data, error } = await supabase
      .from('recurring_booking_occurrences')
      .select('*')
      .eq('recurring_booking_id', recurringId)
      .order('occurrence_date', { ascending: true });

    if (error) throw error;
    return data;
  },

  /**
   * Get pending occurrences (not yet confirmed or skipped)
   */
  async getPendingOccurrences(recurringId: string): Promise<RecurringOccurrence[]> {
    const { data, error } = await supabase
      .from('recurring_booking_occurrences')
      .select('*')
      .eq('recurring_booking_id', recurringId)
      .eq('status', 'pending')
      .gte('occurrence_date', new Date().toISOString())
      .order('occurrence_date', { ascending: true });

    if (error) throw error;
    return data;
  },

  /**
   * Confirm an occurrence (create actual booking)
   */
  async confirmOccurrence(occurrenceId: string): Promise<{ booking_id: string }> {
    const { data, error } = await supabase.rpc('confirm_recurring_occurrence', {
      p_occurrence_id: occurrenceId,
    });

    if (error) throw error;
    return data;
  },

  /**
   * Skip an occurrence
   */
  async skipOccurrence(occurrenceId: string): Promise<RecurringOccurrence> {
    const { data, error } = await supabase
      .from('recurring_booking_occurrences')
      .update({ status: 'skipped' })
      .eq('id', occurrenceId)
      .select()
      .single();

    if (error) throw error;
    return data;
  },

  /**
   * Cancel a single occurrence
   */
  async cancelOccurrence(occurrenceId: string): Promise<RecurringOccurrence> {
    const { data, error } = await supabase
      .from('recurring_booking_occurrences')
      .update({ status: 'cancelled' })
      .eq('id', occurrenceId)
      .select()
      .single();

    if (error) throw error;
    return data;
  },

  /**
   * Regenerate occurrences for a recurring booking
   */
  async regenerateOccurrences(recurringId: string, maxOccurrences = 52): Promise<number> {
    const { data, error } = await supabase.rpc('generate_recurring_occurrences', {
      p_recurring_booking_id: recurringId,
      p_max_occurrences: maxOccurrences,
    });

    if (error) throw error;
    return data as number;
  },
};

// ============================================================================
// React Query Hooks
// ============================================================================

/**
 * Hook to fetch user's recurring bookings
 *
 * @example
 * ```tsx
 * function MyRecurringBookings() {
 *   const { user } = useAuth();
 *   const { data: recurring, isLoading } = useUserRecurring(user?.id!);
 *
 *   if (isLoading) return <LoadingSpinner />;
 *
 *   return (
 *     <div>
 *       {recurring?.map(r => (
 *         <RecurringBookingCard key={r.id} recurring={r} />
 *       ))}
 *     </div>
 *   );
 * }
 * ```
 */
export const useUserRecurring = (
  userId: string,
  enabled = true
): UseQueryResult<RecurringBookingWithOccurrences[], Error> => {
  return useQuery({
    queryKey: recurringKeys.userRecurring(userId),
    queryFn: () => recurringService.getUserRecurring(userId),
    enabled: !!userId && enabled,
    staleTime: 3 * 60 * 1000, // 3 minutes
  });
};

/**
 * Hook to fetch a single recurring booking with occurrences
 */
export const useRecurringBooking = (
  id: string,
  enabled = true
): UseQueryResult<RecurringBookingWithOccurrences, Error> => {
  return useQuery({
    queryKey: recurringKeys.withOccurrences(id),
    queryFn: () => recurringService.getById(id),
    enabled: !!id && enabled,
  });
};

/**
 * Hook to fetch occurrences for a recurring booking
 */
export const useRecurringOccurrences = (
  recurringId: string,
  enabled = true
): UseQueryResult<RecurringOccurrence[], Error> => {
  return useQuery({
    queryKey: recurringKeys.occurrences(recurringId),
    queryFn: () => recurringService.getOccurrences(recurringId),
    enabled: !!recurringId && enabled,
    staleTime: 1 * 60 * 1000, // 1 minute
  });
};

/**
 * Hook to fetch pending occurrences
 */
export const usePendingOccurrences = (
  recurringId: string,
  enabled = true
): UseQueryResult<RecurringOccurrence[], Error> => {
  return useQuery({
    queryKey: [...recurringKeys.occurrences(recurringId), 'pending'],
    queryFn: () => recurringService.getPendingOccurrences(recurringId),
    enabled: !!recurringId && enabled,
    staleTime: 30 * 1000, // 30 seconds
  });
};

/**
 * Hook to create a recurring booking
 *
 * @example
 * ```tsx
 * function CreateRecurringForm() {
 *   const createRecurring = useCreateRecurring();
 *
 *   const handleSubmit = (data: RecurringBookingInsert) => {
 *     createRecurring.mutate(data, {
 *       onSuccess: (recurring) => {
 *         toast.success('Recurring booking created!');
 *         navigate(`/recurring/${recurring.id}`);
 *       }
 *     });
 *   };
 *
 *   return <form onSubmit={handleSubmit}>...</form>;
 * }
 * ```
 */
export const useCreateRecurring = (): UseMutationResult<
  RecurringBooking,
  Error,
  RecurringBookingInsert
> => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: recurringService.create,
    onSuccess: (newRecurring) => {
      // Invalidate user's recurring bookings
      queryClient.invalidateQueries({
        queryKey: recurringKeys.userRecurring(newRecurring.user_id),
      });
    },
  });
};

/**
 * Hook to update a recurring booking
 */
export const useUpdateRecurring = (): UseMutationResult<
  RecurringBooking,
  Error,
  { id: string; updates: RecurringBookingUpdate }
> => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: ({ id, updates }) => recurringService.update(id, updates),
    onSuccess: (updatedRecurring, { id }) => {
      // Invalidate queries
      queryClient.invalidateQueries({ queryKey: recurringKeys.all });
      queryClient.setQueryData(recurringKeys.detail(id), updatedRecurring);
    },
  });
};

/**
 * Hook to pause a recurring booking
 */
export const usePauseRecurring = (): UseMutationResult<RecurringBooking, Error, string> => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: recurringService.pause,
    onSuccess: (_, id) => {
      queryClient.invalidateQueries({ queryKey: recurringKeys.all });
    },
  });
};

/**
 * Hook to resume a recurring booking
 */
export const useResumeRecurring = (): UseMutationResult<RecurringBooking, Error, string> => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: recurringService.resume,
    onSuccess: (_, id) => {
      queryClient.invalidateQueries({ queryKey: recurringKeys.all });
    },
  });
};

/**
 * Hook to cancel a recurring booking
 *
 * @example
 * ```tsx
 * function CancelRecurringButton({ recurringId }: { recurringId: string }) {
 *   const cancelRecurring = useCancelRecurring();
 *
 *   const handleCancel = () => {
 *     if (confirm('Cancel this recurring booking series?')) {
 *       cancelRecurring.mutate(recurringId, {
 *         onSuccess: () => toast.success('Series cancelled')
 *       });
 *     }
 *   };
 *
 *   return <button onClick={handleCancel}>Cancel Series</button>;
 * }
 * ```
 */
export const useCancelRecurring = (): UseMutationResult<RecurringBooking, Error, string> => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: recurringService.cancel,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: recurringKeys.all });
    },
  });
};

/**
 * Hook to confirm an occurrence
 */
export const useConfirmOccurrence = (): UseMutationResult<
  { booking_id: string },
  Error,
  string
> => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: recurringService.confirmOccurrence,
    onSuccess: () => {
      // Invalidate occurrences and bookings
      queryClient.invalidateQueries({ queryKey: recurringKeys.all });
      queryClient.invalidateQueries({ queryKey: ['bookings'] });
    },
  });
};

/**
 * Hook to skip an occurrence
 */
export const useSkipOccurrence = (): UseMutationResult<
  RecurringOccurrence,
  Error,
  string
> => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: recurringService.skipOccurrence,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: recurringKeys.all });
    },
  });
};

/**
 * Hook to cancel a single occurrence
 */
export const useCancelOccurrence = (): UseMutationResult<
  RecurringOccurrence,
  Error,
  string
> => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: recurringService.cancelOccurrence,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: recurringKeys.all });
    },
  });
};
